### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ToddForsberg** [mbdavid/LiteDB.Studio#1]
I realize this is a brand new project so maybe it is not completed yet...

FYI:  I got this error when building the project.

![image](https://user-images.githubusercontent.com/37591206/65530194-17250c80-debd-11e9-9d9b-fff632c6e33c.png)

```
Error	CS0117	'ConnectionMode' does not contain a definition for 'Shared'	LiteDB.Studio
```

![image](https://user-images.githubusercontent.com/37591206/65529710-45eeb300-debc-11e9-9013-0aaa0fa8aaca.png)

```C#
private void BtnConnect_Click(object sender, EventArgs e)
{
    this.ConnectionString.Mode =
        radModeEmbedded.Checked ? ConnectionMode.Embedded :
        radModeShared.Checked ? ConnectionMode.Shared : ConnectionMode.Embedded;

    this.ConnectionString.Filename = txtFilename.Text;
    this.ConnectionString.UtcDate = chkUTC.Checked;
    this.ConnectionString.ReadOnly = chkReadonly.Checked;
    this.ConnectionString.Upgrade = chkUpgrade.Checked;
    this.ConnectionString.Password = txtPassword.Text.Trim().Length > 0 ? txtPassword.Text.Trim() : null;
```

**Comment by mbdavid** [comment]
Hi @ToddForsberg, I saw this error. I need update LiteDB nuget version with current master branch. I'm doing today or tomorrow. I split repos to be easy to work, but now I keep nuget updated!

**Comment by ToddForsberg** [comment]
Thanks.  I'll check back later.
