### ISSUE TITLE
Export to json not working

### ISSUE THREAD

**Issue by Hellfim** [mbdavid/LiteDB.Studio#10]
Hello and thank you for this great tool!
I'm trying to export table into json via generated code
`SELECT $
  INTO $file_json('C:/temp/MyTable.json')
  FROM MyTable;`
and receiving following error:
> System collection '$file_json' are not registered as system collection

How can I overcome this issue?

**Comment by mbdavid** [comment]
Hi! `$file_json` was renamed to `$file`. I'm updating all documentation.

**Comment by Hellfim** [comment]
Great, thanks! The issue is resolved.
