### ISSUE TITLE
v1.0.1 can't run

### ISSUE THREAD

**Issue by chencun** [mbdavid/LiteDB.Studio#11]
Are you miss some files?

v1.0.0 size : 1.11 MB

v1.0.1 size : 529 KB

error:

应用程序: LiteDB.Studio.exe Framework 版本: v4.0.30319 说明: 由于未经处理的异常，进程终止。异常信息:  System.IO.FileNotFoundException 在 LiteDB.Studio.MainForm..ctor(System.String) 在  LiteDB.Studio.Program.Main(System.String[])

**Comment by mbdavid** [comment]
Sorry, wrong upload file. Now I fixed with correct file

**Comment by chencun** [comment]
ok,thanks!
