### ISSUE TITLE
How do i delete delete a document ? 

### ISSUE THREAD

**Issue by DAVIDSystems** [mbdavid/LiteDB.Studio#13]
DELETE FROM CollectionName is not working ? 
Is there any possibility to delete in LiteDB.Studio
I'm using the currrent GitHub version of  LiteDB.Studio

**Comment by mbdavid** [comment]
In delete WHERE is required. (I will fix this in next version)

**Comment by DAVIDSystems** [comment]
Thanks and my greatest respect for the LiteDB library....

**Comment by darcome** [comment]
Can you please give me an example? I've not been able to make it work.

Thanks in advance

**Comment by DAVIDSystems** [comment]
Actuall you need to write: "DELETE articleLinks WHERE _id <> 1;"
The bug is not in the LiteDB.Studio but in the file Delete.cs in the SQL-Parser in LiteDB

`        private BsonDataReader ParseDelete()
        {
            _tokenizer.ReadToken().Expect("DELETE");

           here the line:  _tokenizer.ReadToken().Expect("FROM"); is missing
            var collection = _tokenizer.ReadToken().Expect(TokenType.Word).Value;

            _tokenizer.ReadToken().Expect("WHERE");

            var where = BsonExpression.Create(_tokenizer, _parameters, BsonExpressionParserMode.Full);

            _tokenizer.ReadToken().Expect(TokenType.EOF, TokenType.SemiColon);

            var result = _engine.DeleteMany(collection, where);

            return new BsonDataReader(result);
        }`

**Comment by darcome** [comment]
Hi, I tried "DELETE articleLinks WHERE _id <> 1"

but I recive the following error:

Unexpected token `>` in position 32.

ELETE articleLinks WHERE _id <> 1
-------------------------------^

Can you pleease help me?
Thanks in advance

**Comment by mbdavid** [comment]
Sorry, there is no `<>` as diffente... use .NET syntax `!=`

**Comment by darcome** [comment]
It works! Thank you very much!
