### ISSUE TITLE
What query syntax should I use?

### ISSUE THREAD

**Issue by zblesk** [mbdavid/LiteDB.Studio#2]
I can't seem to figure out how to do even a basic query.

I have Feed records that have a list of Items. 
I'm trying to find any Feed whose Items list has an enrtry where the URL field is 'test'.

I've tried things like this: 

` SELECT $ FROM Feed where $.ITEMS[*].Url = 'test'`

But I always get just
```
Left expression `($.ITEMS[*]=>@.Url)` returns more than one result. Try use ANY or ALL before operant.
```
I have not succeeded in using "ANY" or "ALL" - no idea how. 

When I run just `SELECT $ FROM Feed`, the data looks like this:

```
{
  "_id": "zp",
  "Items": 
  [
    {
      "_id": 1,
      "Read": false,
      "Uri": "a.url"
    },
    {
      "_id": 2,
      "Read": false,
      "Uri": "b.com"
    }
  ]
}
```

What am I missing? How should this be done? Thanks!

**Comment by mbdavid** [comment]
Hi @zblesk, sorry about that, It's missing documentation about SQL syntax. In this case, you must use ANY (or ALL) keyword before equals signal.

`SELECT $ FROM Feed where Items[*].Url ANY = 'test'`
