### ISSUE TITLE
select rows limit 1000

### ISSUE THREAD

**Issue by gothrek** [mbdavid/LiteDB.Studio#20]
its possible see more than 1000 rows from a select?

**Comment by josephinenewbie** [comment]
select $ from TABLE **limit 100**

**Comment by Bluscream** [comment]
This does only show less results, not more!

**Comment by gothrek** [comment]
tks :(

**Comment by Paul-Williams** [comment]
Why was this closed? Is this solved?

**Comment by tjmoore** [comment]
Not solved in the latest version (1.0.2).

`SELECT $ FROM TABLE limit 2000`

and I get 1000.

Same command from LiteDb.Shell and I get all events up to 2000 max.

**Comment by PatrickSachs** [comment]
In case anyone needs it, we needed this feature for ourselves and implemented it in a fork: https://github.com/Sahnee-DE/LiteDB.Studio/releases/tag/v1.0.2-SAHNEE

**Comment by Switch-9867** [comment]
for anyone wondering this does work in the newest version
