### ISSUE TITLE
Delete Syntax

### ISSUE THREAD

**Issue by RichardClaxton** [mbdavid/LiteDB.Studio#22]
Using LiteDB Studio v.1.0.1.0

What would be an example of deleting a record?

I have used SQL like syntax

DELETE FROM jobs WHERE JobId = "025086"

but I get the error message.
Unexpected token `jobs` in position 13. Expected `WHERE`.

DELETE FROM jobs WHERE JobId
-------------^

Its not clear what the syntax should be if I change it to

DELETE WHERE JobId = "025086"

I get the error

Unexpected token `JobId` in position 14. Expected `WHERE`.

DELETE WHERE JobId = "025086"
--------------^

Many Thanks

**Comment by lbnascimento** [comment]
@RichardClaxton No need for `FROM`, just do something like `DELETE jobs WHERE JobId = "025086"`

**Comment by RichardClaxton** [comment]
Thanks that works, thanks for quick response.
