### ISSUE TITLE
Can't figure out the syntax to count or display the number of different values in a column

### ISSUE THREAD

**Issue by WalkerDaleT** [mbdavid/LiteDB.Studio#23]
DISTINCT ColumnName does not seem to be parsable

Select Count(DISTINCT ColumName) from TABLE fails
Select DISTINCT ColumnName from TABLE fails also.

**Comment by WalkerDaleT** [comment]
Actually 
Select Column DISTINCT from TABLE does see to execute, but returns all rows, not just DISTINCT rows.

**Comment by lbnascimento** [comment]
@WalkerDaleT Something like `select distinct(*.Column) from Table` should work.

**Comment by WalkerDaleT** [comment]
Thank you. This issue can be closed.
