### ISSUE TITLE
multiple "group by"

### ISSUE THREAD

**Issue by dsniegocki** [mbdavid/LiteDB.Studio#24]
Hello -

Does the query engine currently support multiple "group by"?  receiving this error:

    Unexpected token `,` in position 112.
    customers  group by gitprovider, plan
    -------------------------------^

...when running this query:

    SELECT distinct(*.gitprovider), 
    distinct(*.plan),
        count(*) as total
    FROM customers
    group by gitprovider, plan

**Comment by lbnascimento** [comment]
@dsniegocki Technically no, but you can achieve it by grouping by a document that contains the fields you want.

```
SELECT @key as group,
       count(*) as total
FROM customers
GROUP BY { gitprovider: $.gitprovider, plan: $.plan }
```

The special field `@key` returns the grouping expression for every group. In a group-by query, you can only select `@key` and aggregate functions over fields.

**Comment by dsniegocki** [comment]
Thank you!
