### ISSUE TITLE
3 engines detected the EXE file as malicious

### ISSUE THREAD

**Issue by valgen** [mbdavid/LiteDB.Studio#25]
Hi guys,

I've checked this file 
**https://github.com/mbdavid/LiteDB.Studio/releases/download/v1.0.1/LiteDB.Studio.exe**
with VirusTotal and got this result:
[https://www.virustotal.com/gui/file/a71f4bf7dc597d7d4d55e3d88d10b40c399f8c04aa4aa617fbbd148a9b0522ae/detection](https://www.virustotal.com/gui/file/a71f4bf7dc597d7d4d55e3d88d10b40c399f8c04aa4aa617fbbd148a9b0522ae/detection)

Should I worry about it?

**Comment by lbnascimento** [comment]
@valgen Not sure why this is happening, but those are clearly false positives. LiteDB and LiteDB.Studio are completely open source, you can check the sources and build the projects yourself if you wish.

**Comment by valgen** [comment]
Hi @lbnascimento,

Thanks for your quick reply.

Maybe someone can consider submitting a false positive request to the 3 engines?
https://www.secureaplus.com/features/antivirus/report-false-positive/
https://www.maxsecureantivirus.com/submit_aFalse_Positive.htm
https://trapmine.com/company/contact-us/

**Comment by lbnascimento** [comment]
@valgen Will do, thanks for the tip.
