### ISSUE TITLE
Can't open db file (LiteDB v5)

### ISSUE THREAD

**Issue by a-a-k** [mbdavid/LiteDB.Studio#27]
I'm trying to open db file but the process fails with next exception:   

```
System.NotSupportedException: BSON type not supported
в LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
в LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
в LiteDB.Engine.HeaderPage.LoadPage()
в LiteDB.Engine.HeaderPage..ctor(PageBuffer buffer)
в LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
в LiteDB.SharedEngine.OpenRead()
в LiteDB.SharedEngine.Query(String collection, Query query)
в LiteDB.LiteQueryable`1.ExecuteReader()
в LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
в System.Linq.Buffer`1..ctor(IEnumerable`1 source)
в System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
в LiteDB.LiteQueryable`1.ToArray()
в LiteDB.Studio.SqlCodeCompletion.UpdateCodeCompletion(LiteDatabase db)
в LiteDB.Studio.MainForm.<Connect>d__6.MoveNext()
```

My db file here

[Recycling.zip](https://github.com/mbdavid/LiteDB.Studio/files/4605697/Recycling.zip)

**Comment by a-a-k** [comment]
@mbdavid please take a look

**Comment by federicoorlandini** [comment]
Same problem here.

**Comment by lbnascimento** [comment]
@a-a-k Your file opens just fine here with LiteDB v5.0.7 (and Studio v1.0.2.0). What version are you using?

**Comment by a-a-k** [comment]
> @a-a-k Your file opens just fine here with LiteDB v5.0.7 (and Studio v1.0.2.0). What version are you using?

I'm using the same versions. Am I doing something wrong?

**Comment by lbnascimento** [comment]
@a-a-k I'm not sure what is happening. This error usually means that the datafile is corrputed, which is weird because it opens fine here - I even looked at the hex dump of each page and there doesn't seem to be any corruption or inconsistency.

Is there a log file for your datafile?

**Comment by a-a-k** [comment]
> Is there a log file for your datafile?

Where do I found it?

**Comment by lbnascimento** [comment]
@a-a-k In the same folder where your datafile is located. It should be called something"-log.db".

**Comment by a-a-k** [comment]
> @a-a-k In the same folder where your datafile is located. It should be called something"-log.db".

there no any log files

**Comment by lbnascimento** [comment]
@a-a-k Can you open this rebuilt datafile?
[Recycling-rebuild.zip](https://github.com/mbdavid/LiteDB.Studio/files/4610336/Recycling-rebuild.zip)

**Comment by a-a-k** [comment]
> @a-a-k Can you open this rebuilt datafile?
> [Recycling-rebuild.zip](https://github.com/mbdavid/LiteDB.Studio/files/4610336/Recycling-rebuild.zip)

I can't even unzip this :(

**Comment by lbnascimento** [comment]
@a-a-k Could you zip and upload the LiteDB and LiteDB.Studio projects you're using to open the datafile?

**Comment by a-a-k** [comment]
I took LiteDB via nuget. Studio was taken as zip from here

[LiteDB.Studio-master.zip](https://github.com/mbdavid/LiteDB.Studio/files/4610862/LiteDB.Studio-master.zip)

**Comment by lbnascimento** [comment]
@a-a-k Does the error happen when you open the file or does it happen when you run a specific query?

**Comment by a-a-k** [comment]
> @a-a-k Does the error happen when you open the file or does it happen when you run a specific query?

when opening the file. may be any settings there not specified correctly?

**Comment by a-a-k** [comment]
@lbnascimento any idea?

**Comment by sohilww** [comment]
I had the same problem, I was using the .exe file beside the .sln file, it uses an old version of lite.db engine...
I built a project and it worked correctly.
for building project check the [Issue 28](https://github.com/mbdavid/LiteDB.Studio/issues/28)

**Comment by a-a-k** [comment]
> I built a project and it's working correctly.
> for building a project check the [Issue 28](https://github.com/mbdavid/LiteDB.Studio/issues/28)
Thank you man! Solved!

**Comment by sunnamed434** [comment]
I have the same problem but only when I try to use this SQL request:
```sql
SELECT $ FROM table limit 4000;
```

logs:
```console
BSON type not supported

===================================================
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.DatafileLookup.Load(PageAddress rawId)
   at LiteDB.Engine.DatafileLookup.Load(IndexNode node)
   at LiteDB.Engine.BasePipe.<LoadDocument>d__6.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at LiteDB.Engine.QueryPipe.<Select>d__2.MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader.Read()
   at LiteDB.Studio.TaskData.ReadResult(IBsonDataReader reader)
   at LiteDB.Studio.MainForm.CreateThread(TaskData task)
```

If I try to:
```sql
SELECT $ FROM table limit 3792;
```

and it works just fine, but anything more than ~3792 fails
