### ISSUE TITLE
Missing LiteDB project in the LiteDB.Studio solution

### ISSUE THREAD

**Issue by federicoorlandini** [mbdavid/LiteDB.Studio#28]
Hi,

If you open the LiteDB.Studio solution, you can see that it includes a LiteDB project which is not present.

**Comment by quicksln** [comment]
Hello. I’m having the same issue.

**Description :**
If you don’t have LiteDB projected already cloned – when cloning LiteDB.Studio, LiteDB.Studio is missing reference to that project. Please see attached print screen for details.
![Annotation 2020-05-12 133039](https://user-images.githubusercontent.com/65227444/81681890-cf0b2800-9454-11ea-8493-800f876e6f24.png)


**Solution :**
LiteDb.Studio could use latest LiteDB reference from Nuget package definition. 

Let me know if this is acceptable solution. I would be happy to contribute 😊

Regards
Piotr

**Comment by quicksln** [comment]
I've created PR fixing this issue.

**Comment by federicoorlandini** [comment]
The pull request is still open. I reviewed it and it looks good. Is there any possibility to see the pull request accepted and merged in master branch?

**Comment by quicksln** [comment]
Hi @federicoorlandini, thank you for reviewing my PR.

Only @mbdavid @lbnascimento project contributors can accept and merge PR into master.
Of course, if they see PR valuable for future project evolution. So we need to be patient and 
wait for response/feedback :)

Cheers
Piotr
