### ISSUE TITLE
Shared mode Failed

### ISSUE THREAD

**Issue by luckymark** [mbdavid/LiteDB.Studio#38]
When a database opened by an app with shared mode, Studio open that database  with shared mode will fail!

**Comment by lbnascimento** [comment]
@luckymark I could not reproduce the issue, Shared mode seems to work just fine here. Could you provide a sequence of steps to reproduce the issue?

**Comment by lbnascimento** [comment]
@luckymark You're using the connection string incorrectly, it should be `Connection=Shared`. For more info, check out the [Connection String documentation](http://www.litedb.org/docs/connection-string/).

**Comment by luckymark** [comment]
@lbnascimento Shared mode works！
Thanks a lot！
