### ISSUE TITLE
Allow tabs to be closed

### ISSUE THREAD

**Issue by tdwright** [mbdavid/LiteDB.Studio#42]
Love the tool - both LiteDB itself and the studio.

I would like to add some functionality to close tabs once opened. Would you welcome a PR?

**Comment by john-bartu** [comment]
@tdwright 
If you talk about query  tabs  like 1,2,3,4... 
You can close those tabs using middle mouse button/ pressing scroll wheel.

**Comment by tdwright** [comment]
Thanks @john-bartu. That wasn't obvious, but your answer solves my problem.

**Comment by waffle-lord** [comment]
It would be cool to have another way to close tabs, since if you don't have a scroll wheel or middle mouse button you won't be able to close them. Like me from my laptop ... :(
