### ISSUE TITLE
Suggestion.. LiteDB.Studio Cross Platform GUI

### ISSUE THREAD

**Issue by felixclase** [mbdavid/LiteDB.Studio#6]
Well, basically what is in title.

https://avaloniaui.net

https://github.com/ElectronNET/Electron.NET

https://www.mono-project.com/docs/gui/gtksharp/

**Comment by mbdavid** [comment]
Hi @felixclase, today another community member create this suggestion:

https://gitlab.com/HankG/litedbportal/

**Comment by felixclase** [comment]
Excellent.

Thanks
