### ISSUE TITLE
Type initializer exception

### ISSUE THREAD

**Issue by raconn** [mbdavid/LiteDB.Studio#63]
Hello - I cloned the latest of the repo. Trying t build on VS 2019 for Mac. Get the following exception. /LiteDB.Studio/packages/MSBuild.ILMerge.Task.1.1.3/build/MSBuild.ILMerge.Task.targets(88,5): error : The type initializer for 'System.Compiler.CoreSystemTypes' threw an exception.

Something I'm doing wrong?

Thanks.

**Comment by gikotim** [comment]
I have the same issue, when compiling on a Mac Air (M2).
What is the solution?

Thanks!
